apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jfsp90u0f-python 
  janus-idp.io/tekton: jfsp90u0f-python
  backstage.io/kubernetes-id: jfsp90u0f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jfsp90u0f-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml